version: "3"
services:
  nodeapi:
    container_name: nodeapi
    image: halljared/mtg-card-tool:nodeapi
    restart: always
    depends_on:
      - db
    environment:
      APP_ENV: "prod"
      MONGODB_DATABASE: mtg_card_tool
      MONGODB_USERNAME: nodeapiuser
      MONGODB_PASSWORD: ezpass
      MONGODB_HOSTNAME: db
    networks:
      - frontend
      - backend
  db:
    container_name: db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: ezrootpass
      MONGO_INITDB_DATABASE: mtg_card_tool
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend
  webserver:
    container_name: webserver
    image: halljared/mtg-card-tool:webserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend

volumes:
  mongodbdata:
    driver: local

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
